image: Ubuntu1804 # образ для сборки
stack: node 12 # окружение
branches:
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - npm install # команда установки зависимостей
build: false
test_script:
  npm run limit && npm test # скрипт сборки